site_name: GEO1003 - Shared Notes
theme:
  name: material
  language: en
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.top
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye


repo_url: https://github.com/ZokszY/GEO1003-Shared_Notes
docs_dir: docs
edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_truly_sane_lists
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  # - git-authors
  - git-committers:
      repository: ZokszY/GEO1003-Shared_Notes
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - caption
  - glightbox

# Define navigation and documentation structure
# This part is automatically updated using docs/notes.txt and docs/books.txt
# Do not edit this part manually: it will be overwritten
nav:
  - Concise notes:
    - Introduction: "content/notes/intro.md"
    - Example:
      - Introduction: "content/notes/example/intro.md"
      - Markdown Basics: "content/notes/example/markdown_basics.md"
      - Empty Section: "content/notes/example/empty_section.md"
    - How does GNSS work?:
      - Introduction: "content/notes/how_does_gnss_work/intro.md"
      - GPS segments: "content/notes/how_does_gnss_work/segments.md"
      - Radio Signal: "content/notes/how_does_gnss_work/signal.md"
      - Initialisation: "content/notes/how_does_gnss_work/initialisation.md"
      - Pseudorange Measurement: "content/notes/how_does_gnss_work/pseudorange.md"
      - Carrier Phase Measurement: "content/notes/how_does_gnss_work/carrier_phase.md"
      - Jamming and Spoofing: "content/notes/how_does_gnss_work/jamming_spoofing.md"
    - GNSS performance:
      - Introduction: "content/notes/gnss_performance/intro.md"
      - Error Sources: "content/notes/gnss_performance/error_sources.md"
      - Accuracy and Precision: "content/notes/gnss_performance/accuracy_precision.md"
      - Dilution of Precision: "content/notes/gnss_performance/dilution_of_precision.md"
      - Availability, Continuity and Integrity: "content/notes/gnss_performance/availability_continuity_integrity.md"
      - PPP-RTK: "content/notes/gnss_performance/ppp_rtk.md"
      - DGNSS: "content/notes/gnss_performance/dgnss.md"
    - GNSS in the built environment (outdoor, indoor and in between):
      - Introduction: "content/notes/gnss_built_environment/intro.md"
    - CRS:
      - Introduction: "content/notes/crs/intro.md"
    - Wi-Fi-monitoring / Fingerprinting:
      - Introduction: "content/notes/wifi/intro.md"
    - Location awareness and privacy:
      - Introduction: "content/notes/privacy/intro.md"
    - PDF version: "pdf/notes.pdf"
  - Long notes:
    - Introduction: "content/notes/intro-long.md"
    - Example:
      - Introduction: "content/notes/example/intro-long.md"
      - Markdown Basics: "content/notes/example/markdown_basics-long.md"
      - Empty Section: "content/notes/example/empty_section-long.md"
    - How does GNSS work?:
      - Introduction: "content/notes/how_does_gnss_work/intro-long.md"
      - GPS segments: "content/notes/how_does_gnss_work/segments-long.md"
      - Radio Signal: "content/notes/how_does_gnss_work/signal-long.md"
      - Initialisation: "content/notes/how_does_gnss_work/initialisation-long.md"
      - Pseudorange Measurement: "content/notes/how_does_gnss_work/pseudorange-long.md"
      - Carrier Phase Measurement: "content/notes/how_does_gnss_work/carrier_phase-long.md"
      - Jamming and Spoofing: "content/notes/how_does_gnss_work/jamming_spoofing-long.md"
    - GNSS performance:
      - Introduction: "content/notes/gnss_performance/intro-long.md"
      - Error Sources: "content/notes/gnss_performance/error_sources-long.md"
      - Accuracy and Precision: "content/notes/gnss_performance/accuracy_precision-long.md"
      - Dilution of Precision: "content/notes/gnss_performance/dilution_of_precision-long.md"
      - Availability, Continuity and Integrity: "content/notes/gnss_performance/availability_continuity_integrity-long.md"
      - PPP-RTK: "content/notes/gnss_performance/ppp_rtk-long.md"
      - DGNSS: "content/notes/gnss_performance/dgnss-long.md"
    - GNSS in the built environment (outdoor, indoor and in between):
      - Introduction: "content/notes/gnss_built_environment/intro-long.md"
    - CRS:
      - Introduction: "content/notes/crs/intro-long.md"
    - Wi-Fi-monitoring / Fingerprinting:
      - Introduction: "content/notes/wifi/intro-long.md"
    - Location awareness and privacy:
      - Introduction: "content/notes/privacy/intro-long.md"
    - PDF version: "pdf/notes-long.pdf"
  - Exams overview: content/exams_overview.md
  - Books notes:
    - Tiberius - 2022 - Surveying and Mapping:
      - 12 - Introduction: "content/books/tiberius/12-intro.md"
      - 13 - Ranging: "content/books/tiberius/13-ranging.md"
      - 14 - Positioning: "content/books/tiberius/14-positioning.md"
      - 15 - GPS positioning modes: "content/books/tiberius/15-gps_positioning_modes.md"
      - 16 - GNSS and applications: "content/books/tiberius/16-gnss_and_applications.md"
    - Indoor Fingerprint Positioning Based on Wi-Fi - An Overview:
      - 1 - Introduction: "content/books/shixiong_xia/notes.md"
      - : "content/books/hexagon_intro_to_GNSS/1-Overview.md"
      - : "content/books/hexagon_intro_to_GNSS/2-Basic GNSS concepts.md"
      - : "content/books/hexagon_intro_to_GNSS/3-GNSS constellations.md"
      - : "content/books/hexagon_intro_to_GNSS/4-GNSS error sources.md"
      - : "content/books/hexagon_intro_to_GNSS/5-Resolving errors.md"
      - : "content/books/hexagon_intro_to_GNSS/6-Sensor fusion.md"
      - : "content/books/hexagon_intro_to_GNSS/7-GNSS threats.md"
      - : "content/books/hexagon_intro_to_GNSS/8-Autonomy.md"
      - 9 - GNSS applications and equipment: "content/books/hexagon_intro_to_GNSS/9-GNSS applications and equipment.md"
