site_name: GEO1003 - Shared Notes
theme:
  name: material
  language: en
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.top
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye


repo_url: https://github.com/ZokszY/GEO1003-Shared_Notes
docs_dir: docs
edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - def_list
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  # - git-authors
  - git-committers:
      repository: ZokszY/GEO1003-Shared_Notes
      branch: main
      token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - caption
  - glightbox

# Define navigation and documentation structure
# This part is automatically updated using docs/notes.txt and docs/books.txt
# Do not edit this part manually: it will be overwritten
nav:
  - Concise notes:
    - Introduction: "content/notes/intro.md"
    - How does GNSS work?:
      - Introduction: "content/notes/how_does_gnss_work/intro.md"
      - GPS segments: "content/notes/how_does_gnss_work/segments.md"
      - Radio Signal: "content/notes/how_does_gnss_work/signal.md"
      - Initialisation: "content/notes/how_does_gnss_work/initialisation.md"
      - Pseudorange Measurement: "content/notes/how_does_gnss_work/pseudorange.md"
      - Carrier Phase Measurement: "content/notes/how_does_gnss_work/carrier_phase.md"
      - Jamming and Spoofing: "content/notes/how_does_gnss_work/jamming_spoofing.md"
    - GNSS performance:
      - Introduction: "content/notes/gnss_performance/intro.md"
      - Error Sources: "content/notes/gnss_performance/error_sources.md"
      - Accuracy and Precision: "content/notes/gnss_performance/accuracy_precision.md"
      - Dilution of Precision: "content/notes/gnss_performance/dilution_of_precision.md"
      - Availability, Continuity and Integrity: "content/notes/gnss_performance/availability_continuity_integrity.md"
      - PPP-RTK: "content/notes/gnss_performance/ppp_rtk.md"
      - DGNSS: "content/notes/gnss_performance/dgnss.md"
    - GNSS in the built environment (outdoor, indoor and in between):
      - Introduction: "content/notes/gnss_built_environment/intro.md"
      - Multipath: "content/notes/gnss_built_environment/multipath.md"
      - Urban Canyon: "content/notes/gnss_built_environment/urban_canyon.md"
      - Shadow Matching: "content/notes/gnss_built_environment/shadow_matching.md"
    - CRS:
      - Introduction: "content/notes/crs/intro.md"
      - Coordinate Systems: "content/notes/crs/coordinate_systems.md"
      - Terrestrial Reference Systems and Frames: "content/notes/crs/terrestrial_reference_frames_systems.md"
      - Datum and Transformations: "content/notes/crs/datum_transformations.md"
      - Map Projections: "content/notes/crs/map_projections.md"
      - RDNAP: "content/notes/crs/rd_nap.md"
    - Wi-Fi-monitoring / Fingerprinting:
      - Introduction: "content/notes/wifi/intro.md"
      - Wi-Fi-Based Approaches: "content/notes/wifi/approaches.md"
      - Radio Signal Based Techniques: "content/notes/wifi/radio_based.md"
      - Hybrid and Other Techniques: "content/notes/wifi/other_techniques.md"
      - Performance Metrics: "content/notes/wifi/performance_metrics.md"
    - Location awareness and privacy:
      - Introduction: "content/notes/privacy/intro.md"
      - Personal Data Protection in the European Union: "content/notes/privacy/european_data.md"
      - Spaces: "content/notes/privacy/spaces.md"
      - IndoorGML: "content/notes/privacy/indoorgml.md"
    - PDF version: "pdf/notes.pdf"
  - Long notes:
    - Introduction: "content/notes/intro-long.md"
    - How does GNSS work?:
      - Introduction: "content/notes/how_does_gnss_work/intro-long.md"
      - GPS segments: "content/notes/how_does_gnss_work/segments-long.md"
      - Radio Signal: "content/notes/how_does_gnss_work/signal-long.md"
      - Initialisation: "content/notes/how_does_gnss_work/initialisation-long.md"
      - Pseudorange Measurement: "content/notes/how_does_gnss_work/pseudorange-long.md"
      - Carrier Phase Measurement: "content/notes/how_does_gnss_work/carrier_phase-long.md"
      - Jamming and Spoofing: "content/notes/how_does_gnss_work/jamming_spoofing-long.md"
    - GNSS performance:
      - Introduction: "content/notes/gnss_performance/intro-long.md"
      - Error Sources: "content/notes/gnss_performance/error_sources-long.md"
      - Accuracy and Precision: "content/notes/gnss_performance/accuracy_precision-long.md"
      - Dilution of Precision: "content/notes/gnss_performance/dilution_of_precision-long.md"
      - Availability, Continuity and Integrity: "content/notes/gnss_performance/availability_continuity_integrity-long.md"
      - PPP-RTK: "content/notes/gnss_performance/ppp_rtk-long.md"
      - DGNSS: "content/notes/gnss_performance/dgnss-long.md"
    - GNSS in the built environment (outdoor, indoor and in between):
      - Introduction: "content/notes/gnss_built_environment/intro-long.md"
      - Multipath: "content/notes/gnss_built_environment/multipath-long.md"
      - Urban Canyon: "content/notes/gnss_built_environment/urban_canyon-long.md"
      - Shadow Matching: "content/notes/gnss_built_environment/shadow_matching-long.md"
    - CRS:
      - Introduction: "content/notes/crs/intro-long.md"
      - Coordinate Systems: "content/notes/crs/coordinate_systems-long.md"
      - Terrestrial Reference Systems and Frames: "content/notes/crs/terrestrial_reference_frames_systems-long.md"
      - Datum and Transformations: "content/notes/crs/datum_transformations-long.md"
      - Map Projections: "content/notes/crs/map_projections-long.md"
      - RDNAP: "content/notes/crs/rd_nap-long.md"
    - Wi-Fi-monitoring / Fingerprinting:
      - Introduction: "content/notes/wifi/intro-long.md"
      - Wi-Fi-Based Approaches: "content/notes/wifi/approaches-long.md"
      - Radio Signal Based Techniques: "content/notes/wifi/radio_based-long.md"
      - Hybrid and Other Techniques: "content/notes/wifi/other_techniques-long.md"
      - Performance Metrics: "content/notes/wifi/performance_metrics-long.md"
    - Location awareness and privacy:
      - Introduction: "content/notes/privacy/intro-long.md"
      - Personal Data Protection in the European Union: "content/notes/privacy/european_data-long.md"
      - Spaces: "content/notes/privacy/spaces-long.md"
      - IndoorGML: "content/notes/privacy/indoorgml-long.md"
    - PDF version: "pdf/notes-long.pdf"
  - Exams overview: content/exams_overview.md
  - Books notes:
    - Tiberius - 2022 - Surveying and Mapping:
      - 12 - Introduction: "content/books/tiberius/12-intro.md"
      - 13 - Ranging: "content/books/tiberius/13-ranging.md"
      - 14 - Positioning: "content/books/tiberius/14-positioning.md"
      - 15 - GPS positioning modes: "content/books/tiberius/15-gps_positioning_modes.md"
      - 16 - GNSS and applications: "content/books/tiberius/16-gnss_and_applications.md"
    - Indoor Fingerprint Positioning Based on Wi-Fi - An Overview:
      - 1 - Introduction: "content/books/shixiong_xia/notes.md"
    - Hexagon - Intro to GNSS:
      - 1 - Overview: "content/books/hexagon_intro_to_GNSS/1-Overview.md"
      - 2 - Basic GNSS concepts: "content/books/hexagon_intro_to_GNSS/2-Basic GNSS concepts.md"
      - 3 - GNSS constellations: "content/books/hexagon_intro_to_GNSS/3-GNSS constellations.md"
      - 4 - GNSS error sources: "content/books/hexagon_intro_to_GNSS/4-GNSS error sources.md"
      - 5 - Resolving error: "content/books/hexagon_intro_to_GNSS/5-Resolving errors.md"
      - 6 - Sensor fusion: "content/books/hexagon_intro_to_GNSS/6-Sensor fusion.md"
      - 7 - GNSS threats: "content/books/hexagon_intro_to_GNSS/7-GNSS threats.md"
      - 8 - Autonomy: "content/books/hexagon_intro_to_GNSS/8-Autonomy.md"
      - 9 - GNSS applications and equipment: "content/books/hexagon_intro_to_GNSS/9-GNSS applications and equipment.md"
    - PPP-RTK Market and Technology Report:
      - 2 - Technical Analysis: "content/books/ppp-rtk_market_and_technology_report/2_technical_analysis.md"
      - 3 - Potential PPP-RTK Based Applications: "content/books/ppp-rtk_market_and_technology_report/3_potential_applications.md"
      - 4 - Competitive Landscape: "content/books/ppp-rtk_market_and_technology_report/4_competitive_landscape.md"
      - 5 - Relevant Standardisation: "content/books/ppp-rtk_market_and_technology_report/5_relevant_standardization.md"
      - 6 - Conclusion: "content/books/ppp-rtk_market_and_technology_report/6_conclusion.md"
    - RDNAPTRANS:
      - Introduction: "content/books/RDNAPTRANS/introduction.md"
      - 2 Transformation from ETRS89 to RD and NAP: "content/books/RDNAPTRANS/2-transformationETRS89toRD-NAP.md"
      - 3 Transformation from RD and NAP to ETRS89: "content/books/RDNAPTRANS/3-transformationRD-NAPtoETRS89.md"
    - Articles about Indoor Positioning:
      - Meshlium Technical Guide - Smartphone Detection: "content/books/indoor_books/meshlium_smartphone_detection.md"
      - Position Location Place and Area - An Indoor Perspective: "content/books/indoor_books/sithole_position_location_plane_area_indoor.md"
    - Lectures:
      - Lecture 1 - Introduction: "content/books/Lectures/lecture1.md"
      - Unknown Title: "content/books/Lectures/lecture2and3.md"
      - Lecture 4 - Network RTK, GNSS Augmentation, GNSS Modernization (GUEST LECTURE): "content/books/Lectures/lecture4.md"
